name: Database Backup

on:
  workflow_dispatch:  # Manuel tetikleme için
  schedule:
    - cron: '0 0 * * *'  # Her gün gece yarısı

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Test Connection
        run: echo "Workflow çalışıyor!" 